services:
  bili-tracker:
    build:
      context: .
      dockerfile: Dockerfile.slim
    container_name: bili-tracker-slim
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      - bili-network

networks:
  bili-network:
    driver: bridge